config:
  allow_missing_modalities: false
  batch_size: 2
  continue_from_most_recent: true
  crop_to_nonzero: true
  deep_supervision: false
  dims: 2D
  experiment: default
  extension: .nii.gz
  learning_rate: 0.001
  loss_fn: DiceCE
  manager_name: ''
  modalities: !!python/tuple
  - MRI
  model_dimensions: 2D
  model_name: TinyUNet
  momentum: 0.99
  norm_op: volume_wise_znorm
  num_classes: 3
  num_modalities: 1
  patch_based_training: true
  patch_size: &id001 !!python/tuple
  - 32
  - 32
  planner_name: demo
  plans: &id002
    allow_missing_modalities: false
    crop_to_nonzero: true
    dataset_properties: {}
    keep_aspect_ratio_when_using_target_size: true
    max_cc_size: 0
    max_n_cc: 0
    mean_cc_size: 0
    mean_n_cc: 0
    min_cc_size: 0
    min_n_cc: 0
    n_foreground_locs:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    new_max_size:
    - 148
    - 186
    - 136
    new_mean_size:
    - 135
    - 177
    - 131
    new_min_size:
    - 127
    - 164
    - 124
    new_sizes:
    - - 148
      - 183
      - 136
    - - 135
      - 183
      - 134
    - - 131
      - 186
      - 131
    - - 139
      - 182
      - 133
    - - 133
      - 173
      - 132
    - - 137
      - 173
      - 133
    - - 136
      - 169
      - 127
    - - 137
      - 174
      - 135
    - - 130
      - 184
      - 130
    - - 130
      - 164
      - 124
    - - 130
      - 179
      - 131
    - - 127
      - 170
      - 125
    - - 131
      - 175
      - 135
    - - 143
      - 177
      - 132
    - - 145
      - 184
      - 131
    new_spacings:
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    - - 1.0
      - 1.0
      - 1.0
    normalization_scheme:
    - volume_wise_znorm
    num_classes: 3
    num_modalities: 1
    plans_name: demo
    preprocessor: null
    suggested_dimensionality: 3D
    target_coordinate_system: RAS
    target_size: null
    target_spacing:
    - 1.0
    - 1.0
    - 1.0
    task_type: segmentation
    transpose_backward:
    - 0
    - 1
    - 2
    transpose_forward:
    - 0
    - 1
    - 2
  plans_name: demo
  plans_path: /Users/zcr545/Desktop/Projects/repos/yucca/tests/data/yucca_preprocessed/TASK000_TEST_SEGMENTATION/demo/demo_plans.json
  save_dir: /Users/zcr545/Desktop/Projects/repos/yucca/tests/data/yucca_models/TASK000_TEST_SEGMENTATION/TinyUNet__2D/__demo/default/kfold_5_fold_0
  split_idx: 0
  split_method: kfold
  split_param: 5
  task: TASK000_TEST_SEGMENTATION
  task_type: segmentation
  train_data_dir: /Users/zcr545/Desktop/Projects/repos/yucca/tests/data/yucca_preprocessed/TASK000_TEST_SEGMENTATION/demo
  version: 0
  version_dir: /Users/zcr545/Desktop/Projects/repos/yucca/tests/data/yucca_models/TASK000_TEST_SEGMENTATION/TinyUNet__2D/__demo/default/kfold_5_fold_0/version_0
  wandb_id: None
deep_supervision: false
disable_inference_preprocessing: true
hparams_path: /Users/zcr545/Desktop/Projects/repos/yucca/tests/data/yucca_preprocessed/TASK000_TEST_SEGMENTATION/demo/demo_plans.json
log_image_every_n_epochs: null
loss_fn: !!python/name:yucca.modules.optimization.loss_functions.nnUNet_losses.DiceCE ''
loss_kwargs:
  soft_dice_kwargs:
    apply_softmax: true
lr_scheduler_kwargs:
  eta_min: 1.0e-09
model_dimensions: 2D
model_kwargs: {}
num_classes: 3
num_modalities: 1
optimizer_kwargs:
  learning_rate: 0.001
  momentum: 0.99
patch_size: *id001
plans: *id002
progress_bar: false
sliding_window_overlap: 0.5
sliding_window_prediction: true
step_logging: false
test_time_augmentation: false
