# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  YUCCA_RAW_DATA: "./yucca_raw_data"
  YUCCA_PREPROCESSED_DATA: "/home/runner/work/yucca/tests/data"
  YUCCA_MODELS: "/home/runner/work/yucca/tests/data"
  YUCCA_RESULTS: "/home/runner/work/yucca/tests/data/"
  YUCCA_SOURCE: "/home/runner/work/yucca/tests/data"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install .
        pip install .[test]
    - name: Lint with flake8
      run: |
        # Check syntax errors
        flake8 yucca --count --select=E9,F63,F7,F82,U100,F841 --show-source --statistics
    - name: Run black
      run: |
        black --check --verbose yucca
    - name: Test with pytest
      run: |
        pytest
#   - name: Get Python changed files
#     id: changed-py-files
#     uses: tj-actions/changed-files@v23
#     with:
#       files: |
#           *.py
#           **/*.py
#   - name: Run if any of the listed files above is changed
#     if: steps.changed-py-files.outputs.any_changed == 'true'
#     run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports
